name: Coverage
on:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    services:
      kafka:
        image: docker.io/bitnami/kafka:3.7
        ports:
          - "9094:9094"
        env:
          KAFKA_CFG_NODE_ID: 0
          KAFKA_CFG_PROCESS_ROLES: controller,broker
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        options: >-
          --health-cmd "kafka-topics.sh --bootstrap-server localhost:9092 --list"
          --health-interval 15s
          --health-timeout 10s
          --health-retries 15
      cassandra:
        image: cassandra:latest
        ports:
          - "9042:9042"
        options: >-
          --health-cmd "cqlsh -e 'SELECT cluster_name FROM system.local;'"
          --health-interval 15s
          --health-timeout 10s
          --health-retries 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install tarpaulin
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-tarpaulin
      - uses: Swatinem/rust-cache@v2
      - name: Run code coverage
        run: |
          cargo tarpaulin --skip-clean --timeout 300 --out Json --output-dir coverage
          echo "COVERAGE=$(jq -r '.coverage | round' coverage/tarpaulin-report.json)" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
          echo "BADGE_PATH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}/coverage-badge.svg" >> $GITHUB_ENV
        env:
          PROSODY_BOOTSTRAP_SERVERS: localhost:9094
      - uses: actions/checkout@v4
        with:
          ref: badges

      # Create the directory where badges will be saved, if needed
      - name: Create destination directory
        env:
          BADGE_PATH: ${{ env.BADGE_PATH }}
        run: mkdir -p "${BADGE_PATH%/*}"

      # Use the output from the `environment` step
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v2.0.3
        id: badge
        with:
          label: 'Coverage'
          status: ${{ env.COVERAGE }}%
          color: 'blue'
          path: ${{ env.BADGE_PATH }}

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: badge
          path: ${{ env.BADGE_PATH }}
          if-no-files-found: error

      - name: Commit badge
        continue-on-error: true
        env:
          BADGE: ${{ env.BADGE_PATH }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${BADGE}"
          git commit -m "Add/Update badge"
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          branch: badges
